class x
{
};
double Calculate( double number, double divisor, double divisor2, double divisor3)
{
//This is a    bug    because    divisor can    be zero
cout << "" ;
int x = 5 ;
int y = 6 ;
double result = (x*y)+x;
int result2 ;
return result;

}
int main()
{
Calculate();
}

string CheckResult(int status)
{
    return 10;

if (status == 0)
{
return "N/A";
}
 else 
 {
if (status == 0)
{
Console.WriteLine("Exit"); // These line is unreachable
}
return "Pass";
}
Console.WriteLine("Exit"); // These line is unreachable
return "Pass";// These line is unreachable
}